name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Setup env File
        env:
          SIMKL_CLIENT_SECRET: ${{ secrets.SIMKL_CLIENT_SECRET }}
          SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
        shell: bash
        run: |
          echo "SIMKL_CLIENT_SECRET=$SIMKL_CLIENT_SECRET" > .env
          echo "SIMKL_CLIENT_ID=$SIMKL_CLIENT_ID" >> .env

      - name: Build Web
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/ --dart-define-from-file=.env

      - name: Create 404.html
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
